### ISSUE TITLE
请问有server.met文件吗？

### ISSUE THREAD

**Issue by bajins** [emulefanscom/ipfilter#1]
从官网下载已经失效了不能下载
迅雷下载文件的时候提示是敏感文件下不了

**Comment by tomchen** [comment]
可以去 https://emule-security.org/ 获取最新的server.met、Ipfilter、Ip-To-Country和nodes.dat

直接链接：
ed2k://|serverlist|[http://upd.emule-security.org/server.met](http://upd.emule-security.org/server.met)|/
https://upd.emule-security.org/ipfilter.zip
https://upd.emule-security.org/ip-to-country.csv.zip
https://upd.emule-security.org/nodes.dat
